Fix version aiohttp
currently, version aiohttp is 4.x which give error
```
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/test/.local/share/virtualenvs/SimpleTradingTool-yYO7YajO/lib/python3.8/site-packages/aiohttp/client.py", line 269, in __del__                                                                     
    if not self.closed:                                                                                                                                                                                            
  File "/home/test/.local/share/virtualenvs/SimpleTradingTool-yYO7YajO/lib/python3.8/site-packages/aiohttp/client.py", line 894, in closed                                                                      
    return self._connector is None or self._connector.closed                                                                                                                                                       
AttributeError: _connector                      
Traceback (most recent call last):                                                                                                                                                                                 
  File "app.py", line 15, in <module>              
    loop.run_until_complete(main())                                                                      
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete                      
    return future.result()                       
  File "app.py", line 9, in main                                                                         
    await bi.async_init()                                                                                
  File "/home/test/github/SimpleTradingTool/core/connect.py", line 11, in async_init                  
    await self._connect()                                                                                
  File "/home/test/github/SimpleTradingTool/core/connect.py", line 14, in _connect                    
    self.client = await AsyncClient.create(                                                              
  File "/home/test/.local/share/virtualenvs/SimpleTradingTool-yYO7YajO/lib/python3.8/site-packages/binance/client.py", line 7122, in create                                                                     
    self = cls(api_key, api_secret, requests_params, tld, testnet, loop)                
  File "/home/test/.local/share/virtualenvs/SimpleTradingTool-yYO7YajO/lib/python3.8/site-packages/binance/client.py", line 7113, in __init__                                                                   
    super().__init__(api_key, api_secret, requests_params, tld, testnet)                                 
  File "/home/test/.local/share/virtualenvs/SimpleTradingTool-yYO7YajO/lib/python3.8/site-packages/binance/client.py", line 156, in __init__                                                                    
    self.session = self._init_session()                                                                  
  File "/home/test/.local/share/virtualenvs/SimpleTradingTool-yYO7YajO/lib/python3.8/site-packages/binance/client.py", line 7140, in _init_session                                                              
    session = aiohttp.ClientSession(                                                                                                                                                                               
TypeError: __init__() got an unexpected keyword argument 'loop' 
```